language: ruby
rvm:
- 2.0.0
services:
- elasticsearch
before_script:
- sudo apt-get install xpdf
- psql -c 'create database emeals_test;' -U postgres
- bin/rake db:setup db:test:prepare
script:
- xvfb-run bin/rake
- bin/rake spec:javascript
after_success:
- bundle exec bin/autodeliver_stories
env:
  global:
  - secure: |-
      n5lSKUy852vhUGTeVaNzWQ8XvAuJgE0JR0wFhBRLZwYbF0SR1vlXTPykup2g
      tHSHdzys91gejqgl+3RJ/t6In4Eq102qCTe2O+xUoYavl9vr9CY4d2QwKfg7
      84lDZGIYRVu4yveQVT+EZFdna0iUAkMs06pGC7g56TOMP7/H9Q8=
deploy:
  provider: heroku
  api_key:
    secure: CbzE+783uWof0830seJMVaGs6dLglVQU2z7164SoRIXI5CiBjcnAWlWYQVIvjns8NIHix08Ne+nx6rfVFwUUj83enxY1WW67hVsaZZXoUVZVh0kH9tlX8knxLum/2xzVj5oOTAO/Yk5so1GakxPNyMj/VQYHw1yimH0UpXR1/9g=
  app: emeals-staging
  on:
    repo: mjm/emeals-web
  run:
  - "rake db:migrate tire:import:all"
  - restart
