---
language: ruby
rvm:
- 2.0.0
before_script:
- sudo apt-get install xpdf qt4-default
- psql -c 'create database emeals_test;' -U postgres
- bin/rake db:setup db:test:prepare
script:
- xvfb-run bin/rake
after_success:
- ruby bin/travis_after_success
- ruby bin/autodeliver_stories
env:
  global:
  - secure: |-
      YN42RDCnKtIFZUQ/CwUbK1t1P2G19pAdJPKc0kJwcYWEQXbKvOSwA0Ek78Bx
      JseGCzq5OmnDyZ7IAQBC2g/oHg4WeDIKVYuhjeO0qyFmq6YmvTW11sg++jjW
      w3ZDQiISaMFISqz7PtTy7Adw6NLKyhAVSwP3mbWNuQ1bVQ4AgrY=
  - secure: |-
      n5lSKUy852vhUGTeVaNzWQ8XvAuJgE0JR0wFhBRLZwYbF0SR1vlXTPykup2g
      tHSHdzys91gejqgl+3RJ/t6In4Eq102qCTe2O+xUoYavl9vr9CY4d2QwKfg7
      84lDZGIYRVu4yveQVT+EZFdna0iUAkMs06pGC7g56TOMP7/H9Q8=
